ITEM.name = "9x18mm"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.ammo = "ar2" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of blaster ammo."
ITEM.longdesc = "This contains en."
ITEM.price = 600
ITEM.busflag = {"ammo"}
ITEM.img = Material("vgui/hud/9x18.png")
ITEM.weight = 0.016
ITEM.isAmmo = true